version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_tests:
    image: postgres:15
    container_name: postgres_db_tests
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2606QWmg
      POSTGRES_DB: tests
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_tests:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_tests: