"""empty message

Revision ID: 5a2819ae4f68
Revises: f9ad0e02ec69
Create Date: 2025-05-28 11:11:51.967781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2819ae4f68'
down_revision: Union[str, None] = 'f9ad0e02ec69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreements', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('backups', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contacts', 'father_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contacts', 'position',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contracts', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contracts', 'theme',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('contracts', 'evolution',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('form_of_ownership', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('objects', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('project_statuses', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_statuses', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('objects', 'code',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('form_of_ownership', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('contracts', 'evolution',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('contracts', 'theme',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contracts', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'position',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'father_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('backups', 'email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('agreements', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
