"""empty message

Revision ID: c359fdb629df
Revises: 
Create Date: 2025-04-22 00:55:15.967652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c359fdb629df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_of_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_of_ownership_id'), 'form_of_ownership', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_table('project_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_statuses_id'), 'project_statuses', ['id'], unique=False)
    op.create_table('web_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('role', sa.String(), server_default='user', nullable=True),
    sa.Column('notification', sa.Boolean(), nullable=True),
    sa.Column('tg_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('telegram'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_web_user_email'), 'web_user', ['email'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form'], ['form_of_ownership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_schema',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['web_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ui_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['web_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_component', 'user_ui_preferences', ['user_id', 'component'], unique=True)
    op.create_index(op.f('ix_user_ui_preferences_id'), 'user_ui_preferences', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('father_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('executor', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=256), nullable=True),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('evolution', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['executor'], ['web_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_id'), 'agreements', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object', sa.Integer(), nullable=True),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('main_executor', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['main_executor'], ['web_user.id'], ),
    sa.ForeignKeyConstraint(['object'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['status'], ['project_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('project_executors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user'], ['web_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_executors_id'), 'project_executors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_executors_id'), table_name='project_executors')
    op.drop_table('project_executors')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_agreements_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_table('contracts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_user_ui_preferences_id'), table_name='user_ui_preferences')
    op.drop_index('ix_user_component', table_name='user_ui_preferences')
    op.drop_table('user_ui_preferences')
    op.drop_table('token_schema')
    op.drop_table('customers')
    op.drop_index(op.f('ix_web_user_email'), table_name='web_user')
    op.drop_table('web_user')
    op.drop_index(op.f('ix_project_statuses_id'), table_name='project_statuses')
    op.drop_table('project_statuses')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_form_of_ownership_id'), table_name='form_of_ownership')
    op.drop_table('form_of_ownership')
    op.drop_table('backups')
    # ### end Alembic commands ###
