"""empty message

Revision ID: f9ad0e02ec69
Revises: c359fdb629df
Create Date: 2025-05-20 12:26:07.973854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ad0e02ec69'
down_revision: Union[str, None] = 'c359fdb629df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contacts', 'customers', ['customer'], ['id'])
    op.create_foreign_key(None, 'contracts', 'customers', ['customer'], ['id'])
    op.alter_column('objects', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    # ### end Alembic commands ###
