"""initial migration

Revision ID: b965ab6679e4
Revises: 7de06a6965f0
Create Date: 2025-03-13 22:26:42.220744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b965ab6679e4"
down_revision: Union[str, None] = "7de06a6965f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract")
    op.add_column("web_user", sa.Column("father_name", sa.String(), nullable=True))
    op.add_column("web_user", sa.Column("birthday", sa.Date(), nullable=True))
    op.add_column("web_user", sa.Column("notification", sa.Boolean(), nullable=True))
    op.add_column("web_user", sa.Column("tg_user_id", sa.Integer(), nullable=True))
    op.alter_column("web_user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("web_user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("web_user", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("web_user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "web_user",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'user'::character varying"),
    )
    op.drop_constraint("web_user_login_key", "web_user", type_="unique")
    op.drop_column("web_user", "middle_name")
    op.drop_column("web_user", "login")
    op.drop_column("web_user", "birthdate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "web_user",
        sa.Column("birthdate", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "web_user",
        sa.Column("login", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "web_user",
        sa.Column("middle_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("web_user_login_key", "web_user", ["login"])
    op.alter_column(
        "web_user",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'user'::character varying"),
    )
    op.alter_column("web_user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("web_user", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("web_user", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "web_user", "first_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("web_user", "tg_user_id")
    op.drop_column("web_user", "notification")
    op.drop_column("web_user", "birthday")
    op.drop_column("web_user", "father_name")
    op.create_table(
        "contract",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("contract_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("object_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("customer", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("executer", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "contract_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("stage", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("contract_scan", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("original_scan", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "percent_complite",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("date_start", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("date_finish", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("cost", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("money_received", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("money_left", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "scan_complited_act",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "original_complited_act",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("volumes", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="contract_pkey"),
        sa.UniqueConstraint("contract_code", name="contract_contract_code_key"),
    )
    # ### end Alembic commands ###
