name: Lint with Black

on:
  # Запуск при создании pull request или пуше в ветки
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Устанавливаем зависимости
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Запускаем Black
      - name: Run Black
        run: black --check .
