name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black --check .

      - name: Print Python Path
        run: |
          python -c "import sys; print(sys.path)"

      - name: Print Current Working Directory
        run: |
          pwd
          ls -la

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Run Application with Docker Compose
        run: docker-compose up --build -d

      - name: Wait for Application to Start
        run: |
          until curl -s http://localhost:8000/health-check; do
            echo "Waiting for application to start..."
            sleep 2
          done

      - name: Run Tests
        run: pytest tests
        env:
          DATABASE_URL: postgresql+asyncpg://testuser:testpass@localhost:5432/testdb

      - name: Stop Docker Compose
        run: docker-compose down